branches:
  only:
  - master
  - "/^release\\/.+$/"
language: node.js
node_js:
- node
cache:
  directories:
  - node_modules
sudo: false
before_install:
- openssl aes-256-cbc -K $encrypted_3f2dabfde256_key -iv $encrypted_3f2dabfde256_iv
  -in travis_key.enc -out travis_key -d
- eval "$(ssh-agent -s)"
- cp .travis/id_rsa ~/.ssh/deploy_rsa
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa
install:
- npm install
jobs:
  include:
  - stage: Linter
    name: Running linter
    script:
    - npx eslint src/
  - stage: Build
    name: Build
    script:
    - npm run-script build
deploy:
  - provider: script
    skip_cleanup: true
    script:
    - scp :/dist root@167.99.214.209:/frontend
    on:
      branch:
        - "/^release\\/.+$/"

