branches:
  only:
  - master
  - develop
  - "/^release\\/.+$/"
addons:
  ssh_known_hosts:
  - 167.99.214.209
language: node.js
node_js:
- node
cache:
  directories:
  - node_modules
sudo: false
before_deploy:
- mkdir .ssh
- openssl aes-256-cbc -K $encrypted_3f2dabfde256_key -iv $encrypted_3f2dabfde256_iv -in travis_key.enc -out .ssh/id_rsa -d
- openssl aes-256-cbc -K $encrypted_7be9aed6de09_key -iv $encrypted_7be9aed6de09_iv -in travis_key.pub.enc -out .ssh/id_rsa.pub -d
- eval "$(ssh-agent -s)"
- chmod 600 .ssh/id_rsa
- chmod 600 .ssh/id_rsa.pub
- ssh-add .ssh/id_rsa
install:
- npm install
jobs:
  include:
  - stage: Linter
    name: Running linter
    script:
    - npx eslint src/
  - stage: Build
    name: Building application
    script:
    - npm run-script build
    deploy:
    - provider: script
      skip_cleanup: true
      script:
      - scp -r dist/* www-data@167.99.214.209:/var/www/movie-quotes.ru/html
      on:
        branch: master
