branches:
  only:
  - master
  - "/^release\\/.+$/"
addons:
  ssh_known_hosts:
  - 167.99.214.209
language: node.js
node_js:
- node
cache:
  directories:
  - node_modules
sudo: false
install:
- npm install
jobs:
  include:
    stage: Frontend
    name: Linting and building frontend
    script:
    - npx eslint src/
    - npm run-script build
  before_deploy:
  - pwd
  - ls
  - ls dist
  - ls ./dist
  - mkdir .ssh
  - openssl aes-256-cbc -K $encrypted_3f2dabfde256_key -iv $encrypted_3f2dabfde256_iv -in travis_key.enc -out .ssh/id_rsa -d
  - openssl aes-256-cbc -K $encrypted_7be9aed6de09_key -iv $encrypted_7be9aed6de09_iv -in travis_key.pub.enc -out .ssh/id_rsa.pub -d
  - eval "$(ssh-agent -s)"
  - chmod 600 .ssh/id_rsa
  - chmod 600 .ssh/id_rsa.pub
  - ssh-add .ssh/id_rsa
  deploy:
  - provider: script
    skip_cleanup: true
    script:
    - scp -r dist root@167.99.214.209:/root/frontend
    on:
      branch: release/0.1.1

