export const SHOW_LOADING_HOVER = 'SHOW_LOADING_HOVER';
export const HIDE_LOADING_HOVER = 'HIDE_LOADING_HOVER';

export const SHOW_ERROR = 'SHOW_ERROR';
export const HIDE_ERROR = 'HIDE_ERROR';

export const LOAD_USER = 'LOAD_USER';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const SEARCH_MATCHES = 'SEARCH_MATCHES';

export const SAVE_WATCH_TO_HISTORY = 'SAVE_WATCH_TO_HISTORY';
export const SHOW_WATCH_HISTORY = 'SHOW_WATCH_HISTORY';
